### ISSUE TITLE
LoadButtonData has a field called "tags" - what goes in it?

### ISSUE THREAD

**Issue by jeshyr** [jeshyr/ButtonUp#22]
We store it in an array of strings, enum would be better if it's a fixed list

**Comment by blackshadowshade** [comment]
Tags are currently unused, as far as I know.

**Comment by blackshadowshade** [comment]
See https://github.com/buttonmen-dev/buttonmen/issues/1211

**Comment by jeshyr** [comment]
Awesome. Since the answer is at least currently "nothing important" I shalll ignore this one :)
